---
 nEph: 1
 Eph_max: 10
 limit_height: 40
 limit_size: 40  
 size_pop: 3
 size_gen: 3
 size_gen_edda: 500
 cat_number_len: 6
 cat_number_fit: 6
 cat_number_height: 6
 fit_scale: 0.5
 fit_tol: 0.0000000001
 save_gen: True
 save_pop: True
 mutpb: 0.25
 cxpb: 0.75
 cx_lim: 0.75
 ntot: 30
 num_demes: 300
 inds_to_pass: 1
 size_pop_demes: 100
 size_gen_demes: 5
 threshold_features: 50
 threshold_instances: 1000
 test_perc: 0.2
 val_perc: 0.2
 save_path: "results/"
 NgenesMax: 7
 stdCxpb: 0.7