---
# Common parameters
 nEph: 5                      # number of ephemeral constants
 Eph_max: 10                  # maximum value of the ephemeral constants
 limit_height: 40             # limit height (depth) of GP tree
 limit_size: 40               # limit size (number of nodes) of GP tree
 size_pop: 300                # number of individuals in the population
 size_gen: 300               # number of generations
 mutpb: 0.2                   # mutation probability
 cxpb: 0.8                    # crossover probability
 init_repeat: 100             # number of iterations of the population initialization loop
 cx_lim: 0.75                 # max crossover probability reached when lowering mutation probability and increasing crossover one
 fit_tol: 0.0000000001        # tolerance on fitness to stop evolutionary process
 ntot: 30                     # number of evolutionary processes to perform

 # save parameters
 save_gen: True               # flag to save individuals each generation
 save_pop: True               # flag to save whole population each generation
 save_path: "results/"        # path where to save data






